### ISSUE TITLE
`java.lang.RuntimeException: For input string: "8111""` error during startup causes agent to fail

### ISSUE THREAD

**Issue by agc93** [JetBrains/teamcity-docker-minimal-agent#5]
Running the `teamcity-minimal-agent` image from the following Docker Compose:

```yaml
version : '2'

services:
  server:
    image: 'jetbrains/teamcity-server'
    ports:
      - 8111:8111
    environment:
      - TEAMCITY_SERVER_MEM_OPTS="-Xmx750m"
  agent:
    image: 'jetbrains/teamcity-minimal-agent'
    environment:
      - SERVER_URL="server:8111" # note the quoting here
```

results in the TeamCity server starting correctly, but the agent fails with the following error:

```bash
[2017-01-28 13:16:50,232]  ERROR - s.buildServer.agent.AgentMain2 - Failed to start build agent. For input string: "8111""
java.lang.RuntimeException: For input string: "8111""
        at jetbrains.buildServer.xmlrpc.XmlRpcFactory.createCommonsHttpTransportTarget(XmlRpcFactory.java:63)
        at jetbrains.buildServer.xmlrpc.XmlRpcFactory.create(XmlRpcFactory.java:81)
        at jetbrains.buildServer.agent.impl.XmlRpcAgentLogListener.createTarget(XmlRpcAgentLogListener.java:56)
        at jetbrains.buildServer.agent.impl.XmlRpcAgentLogListener.<init>(XmlRpcAgentLogListener.java:52)
        at jetbrains.buildServer.agent.impl.XmlRpcAgentLogListener.<init>(XmlRpcAgentLogListener.java:43)
        at jetbrains.buildServer.agent.impl.ServerXmlRpcProxy.<init>(ServerXmlRpcProxy.java:37)
        at jetbrains.buildServer.agent.impl.BuildAgentImpl.init(BuildAgentImpl.java:805)
        at jetbrains.buildServer.agent.AgentMain2.startAgent(AgentMain2.java:211)
        at jetbrains.buildServer.agent.AgentMain2.main2(AgentMain2.java:76)
        at jetbrains.buildServer.agent.AgentMain2.main(AgentMain2.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at jetbrains.buildServer.agent.AgentMain.main(AgentMain.java:43)
[2017-01-28 13:16:50,235]   INFO - ent.impl.upgrade.AgentExitCode - Agent exited. Failed to start build agent
```

The full agent log can be found here: https://gist.github.com/agc93/4ccab49938011d7898f03e4c59346b20

This seems to occur whenever the value for `SERVER_URI` passed into the agent is quoted. Removing the quotes (i.e. `- SERVER_URL=server:8111`) seems to work fine. Is this expected behaviour?

**Comment by elvetemedve** [comment]
I noticed a similar, but different problem.

When port is given in the URL `- SERVER_URL=http://teamcity-server:8111`, then the agent ignores it and tries to connect to the port 80 which will obviously fail.
```
[2017-01-31 00:07:29,266]   INFO - buildServer.AGENT.registration - Registering on server via URL http://teamcity-server. AgentDetails{Name='', AgentId=null, BuildId=null, AgentOwnAddress='null', AlternativeAddresses=[172.17.0.5], Port=9090, Version='42538', PluginsVersion='NA', AvailableRunners=[], AvailableVcs=[], AuthorizationToken='', PingCode='2lfG2I7cmQMpo6eNESEWcAUtxRzUblRa'} 
[2017-01-31 00:07:29,306]   WARN - buildServer.AGENT.registration - Error while asking server for the communication protocols via URL http://teamcity-server/app/agents/protocols. Will try all protocols: java.net.ConnectException: Connection refused (enable debug to see stacktrace) 
[2017-01-31 00:07:29,307]   INFO - buildServer.AGENT.registration - Trying to register on server using 'polling' protocol. 
[2017-01-31 00:07:29,370]   INFO - buildServer.AGENT.registration - Registration using 'polling' protocol failed: java.net.ConnectException: Connection refused (enable debug to see stacktrace) 

```

**Comment by VladRassokhin** [comment]
@elvetemedve such case work fine for me:
```
version : '2'

services:
  agent:
    image: 'jetbrains/teamcity-minimal-agent'
    environment:
      - SERVER_URL=http://unit-421.labs.intellij.net:8111
```
Agent (10.0.4) successfully connects to server (10.0.4). Event if server address specified without domain.
Could you please provide part of your docker-compose.yml?
I'm using docker-compose version 1.10.0.

**Comment by elvetemedve** [comment]
Hi @VladRassokhin,
 
As I see the only difference is that I'm using the *first* version of Docker Compose Yaml. However Docker Composer version is the same (1.10.0) for me as well.

```yaml
mysql:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=top-secret
        - MYSQL_DATABASE=teamcity
    volumes:
        - /var/lib/mysql-teamcity:/var/lib/mysql

teamcity:
    container_name: teamcity-server
    image: jetbrains/teamcity-server
    volumes:
        - ./teamcity-data:/data/teamcity_server/datadir
        - /var/log:/opt/teamcity/logs
    ports:
        - "8111:8111"
    links:
        - mysql:db

agent:
    container_name: teamcity-build-agent
    image: jetbrains/teamcity-minimal-agent
    volumes:
        - ./teamcity-agent-data:/data/teamcity_agent/conf
    environment:
        - SERVER_URL=http://teamcity-server:8111
    links:
        - teamcity
```

**Comment by elvetemedve** [comment]
I can confirm that this image woks well with Docker Compose Yaml v2.1.

**Comment by agc93** [comment]
@elvetemedve @VladRassokhin I'm still seeing the same issue with it failing when the URL is quoted, even in 2.1 format

**Comment by elvetemedve** [comment]
@agc93 I have re-created the application stack with quoted environment variable value
```
environment:
          - SERVER_URL="http://teamcity-server:8111"
```
and it works well, the builder is connected to the Teamcity server.

URL in the agent configuration looks like below:
`docker exec teamcity-build-agent cat /data/teamcity_agent/conf/buildAgent.properties | grep serverUrl`
```
## Example:  serverUrl=https://buildserver.mydomain.com:8111
serverUrl=http\://teamcity-server\:8111
```

**Comment by VladRassokhin** [comment]
Seems it's docker-compose problem, yet anyway I've [added](https://github.com/JetBrains/teamcity-docker-minimal-agent/commit/63b5cef6b483378fd4068286160978bc57e8ac24) code to run-agent.sh which would simplify duplicated double quotes.

**Comment by gromilQaaaa** [comment]
Still appears in ubuntu jetbrains/teamcity-agent:2019.2.3

When I use:
- SERVER_URL="teamcity-server:8111"
